from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping, Sequence

import numpy as np

from .core import SpeciesEdges, spearman_rho
from .inference import MeanBootstrapResult, centered_species_bootstrap_mean_test
from .transfer import PreparedTransfer, prepare_transfer


@dataclass(frozen=True)
class PairedControlTransferResult:
    """Held-out transfer skill incremental to a trait-free geometry control."""

    statistic: float
    species_scores: Mapping[str, float]
    boundary_scores: Mapping[str, float]
    opportunity_scores: Mapping[str, float]
    n_eval_species: int


@dataclass(frozen=True)
class PairedControlBootstrapResult:
    observed: PairedControlTransferResult
    species_scores: np.ndarray
    bootstrap: MeanBootstrapResult

    @property
    def p_value(self) -> float:
        return float(self.bootstrap.p_value)


def _train_vector(
    prepared: PreparedTransfer,
    train_turnover: Mapping[str, np.ndarray],
) -> np.ndarray:
    values = np.empty(max(sl.stop for sl in prepared.train_slices.values()), dtype=float)
    for species in prepared.train_species:
        sl = prepared.train_slices[species]
        x = np.asarray(train_turnover[species], dtype=float)
        if x.shape != (sl.stop - sl.start,):
            raise ValueError(f"train turnover shape drift for {species}")
        values[sl] = x
    return values


def score_paired_opportunity_control(
    prepared: PreparedTransfer,
    *,
    train_turnover: Mapping[str, np.ndarray],
    eval_turnover: Mapping[str, np.ndarray],
) -> PairedControlTransferResult:
    """Score boundary transfer beyond the identical train-geometry opportunity field.

    For each held-out species s,

        delta_s = rho(boundary_exposure_s, turnover_s)
                  - rho(opportunity_exposure_s, turnover_s).

    The opportunity exposure is completely trait-free: it is the kernel support
    generated by the same training-species coordinates, weights, bandwidth, and
    edge integration used by the boundary model.  The contrast therefore asks
    whether training *turnover values* add predictive information beyond where
    the training sampling geometry alone places support.
    """
    train_values = _train_vector(prepared, train_turnover)
    delta: dict[str, float] = {}
    boundary: dict[str, float] = {}
    opportunity: dict[str, float] = {}
    for species in prepared.eval_species:
        target = np.asarray(eval_turnover[species], dtype=float)
        predicted = prepared.eval_projection[species] @ train_values + prepared.eval_prior_offset[species]
        support = np.asarray(prepared.eval_opportunity[species], dtype=float)
        if target.shape != predicted.shape or support.shape != predicted.shape:
            raise ValueError(f"evaluation geometry/turnover shape drift for {species}")
        b = spearman_rho(predicted, target)
        o = spearman_rho(support, target)
        boundary[species] = float(b)
        opportunity[species] = float(o)
        delta[species] = float(b - o) if np.isfinite(b) and np.isfinite(o) else float("nan")

    finite = np.asarray([value for value in delta.values() if np.isfinite(value)], dtype=float)
    if len(finite) == 0:
        raise ValueError("no finite paired-control held-out species scores")
    return PairedControlTransferResult(
        statistic=float(finite.mean()),
        species_scores=delta,
        boundary_scores=boundary,
        opportunity_scores=opportunity,
        n_eval_species=int(len(finite)),
    )


def paired_opportunity_control_test(
    train_edges: Sequence[SpeciesEdges],
    eval_edges: Sequence[SpeciesEdges],
    *,
    bandwidth: float,
    prior_strength: float = 0.25,
    prior_mean: float = 0.5,
    segment_points: int = 5,
    n_bootstrap: int = 1999,
    seed: int = 0,
) -> PairedControlBootstrapResult:
    """Centered held-out-species bootstrap for opportunity-incremental transfer."""
    if len(eval_edges) < 6:
        raise ValueError("paired-control inference requires at least six held-out species")
    prepared = prepare_transfer(
        train_edges,
        eval_edges,
        bandwidth=bandwidth,
        prior_strength=prior_strength,
        prior_mean=prior_mean,
        segment_points=segment_points,
    )
    train_turnover = {edges.species: edges.turnover for edges in train_edges}
    eval_turnover = {edges.species: edges.turnover for edges in eval_edges}
    observed = score_paired_opportunity_control(
        prepared,
        train_turnover=train_turnover,
        eval_turnover=eval_turnover,
    )
    scores = np.asarray(
        [observed.species_scores[name] for name in prepared.eval_species if np.isfinite(observed.species_scores[name])],
        dtype=float,
    )
    if len(scores) < 6:
        raise ValueError("fewer than six finite paired-control species scores")
    bootstrap = centered_species_bootstrap_mean_test(
        scores,
        n_bootstrap=n_bootstrap,
        seed=seed,
    )
    if not np.isclose(observed.statistic, bootstrap.observed_mean, atol=1e-12, rtol=0.0):
        raise RuntimeError("paired-control macro-average drift")
    return PairedControlBootstrapResult(
        observed=observed,
        species_scores=scores,
        bootstrap=bootstrap,
    )
